server:
   port: 7001
spring:
   application:
      name: config-server
   cloud:
      config:
         server:
            git:
               uri: https://github.com/YeYunxuan/Config
               search-paths: configs-dir
               username: 1690426539@qq.com
               password: zxw1008611
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/